//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project18.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public System.DateTime LastVisit { get; set; }
        public System.DateTime OpenDate { get; set; }
        public System.DateTime CloseDate { get; set; }
        public string Desc { get; set; }
        public string PhotoUri { get; set; }
        public double X { get; set; }
        public double Y { get; set; }
    }
}
