//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TillsammensWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string MailAddress { get; set; }
        public string LastVisit { get; set; }
        public string X { get; set; }
        public string Y { get; set; }
        public string Desc { get; set; }
        public string FriendList { get; set; }
    }
}
